# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

hostname: demo1.vccw
ip: 192.168.55.121
version: latest
lang: ja
db_host: 192.168.55.121
theme: ''

theme_unit_test: false
theme_unit_test_uri: https://raw.githubusercontent.com/WPTRT/theme-unit-test/master/themeunittestdata.wordpress.xml

wp_i18n_tools: false
mailcatcher: false
plugins: []
wp_cli_packages: []
npms: []
composers: []
ruby_gems: []
